# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'a5' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for a5
  pod 'SwiftyJSON'
  pod 'Alamofire', '~> 5.5'
  pod "SwiftSpinner"
end
